//
// Created by Nathan Bollom on 15/1/20.
//

#include "material.h"

#include <utility>

bool Material::db_checked = false;

Material::Material() {
    // TODO: create new material in db and populate id from autogenerated pk
}

Material::Material(uint32_t id, std::string name, std::string description) : _id(id), _name(std::move(name)), _description(std::move(description)) {

}

uint32_t Material::ID() {
    return _id;
}

std::string Material::Name() {
    return _name;
}

std::string Material::Description() {
    return _description;
}

void Material::setName(std::string name) {
    _name = std::move(name);
}

void Material::setDescription(std::string description) {
    _description = std::move(description);
}

void Material::Save() {
    CheckAndUpdateDBTable();
    // TODO: save changes to the db
}

Material * Material::Load(uint32_t id) {
    CheckAndUpdateDBTable();
    // TODO: load from db and return
    return nullptr;
}

void Material::CheckAndUpdateDBTable() {
    if (!db_checked) {
        // TODO: check registry to see if table exists/latest version
        // TODO: if not, initialise db table
        // TODO: if not latest version then update
        db_checked = true;
    }
}
